config/routes.rb
Railsgirls::Application.routes.draw do

  resources :listings

  get "pages/home"
  get "pages/about"

   root 'pages#home'

     get 'about' => 'pages#about'
     get 'home' => 'pages#home'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider
  belongs_to :user
  def twitter
raise omni = request.env["omniauth.auth"].to_yaml
end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable    
  has_many :authentications
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else

        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end

    end
  end        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all
    render 'index'
  end

  def show
    @listing = Listing.find(params[:id])
    render 'show'
  end

  def new
    @listing = Listing.new
    render 'new'
  end

  def edit
    @listing = Listing.find(params[:id])
    render 'edit'
  end

  def create
    @listing = Listing.new(listing_params)

    if @listing.save
      redirect_to @listing, notice: 'Listing was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to @listing, notice: 'Listing was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to listings_url, notice: 'Listing was successfully destroyed.'
  end

  private
  # Only allow a trusted parameter "white list" through.
  def listing_params
    params.require(:listing).permit(:name, :description, :picture)
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
def twitter
    auth = env["omniauth.auth"]

    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Rails Girls Perth</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      	<li><%= link_to "home", home_path %></li>
        <li><a href="/listings">listings</a></li>
        <li><%= link_to "about", about_path %></li>
        
      </ul>
    </div>
  </div>
</nav>

	
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, Ruby on Rails!</h1>
        <p>I am learning Ruby on Rails, yay</p>
        <p><%= link_to "find out more", about_path, class: "btn btn-primary btn-lg", role: "button" %></p>
      </div>
    </div>

    <div class="container">
    	
<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>
	</div>

    <div class="container">
		<%= yield %>
	</div>

	<footer class="container">
        <p>&copy; Teresa 2014</p>
      </footer>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listings</h1>

<%= link_to 'New Listing', new_listing_path, class: "btn btn-lg btn-success" %>

<% @listings.each do |listing| %>
<div class="listing">
  <h2><%= listing.name %></h2>
  <p><%= listing.description %></p>
  <div class="buttons">
    <%= link_to 'Show', listing, class: "btn btn-primary" %>
    <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-info" %>
    <%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>

<% end %>

<br>



<br>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @listing.picture %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean volutpat nibh in sapien sollicitudin, ac congue velit facilisis. Nulla sollicitudin, leo id luctus tempus, diam dolor bibendum diam, eget malesuada neque mauris nec felis. Proin risus dolor, posuere sit amet nisl sed, dignissim consectetur odio. Duis pharetra ante ac ante faucibus, at ullamcorper enim blandit. Vestibulum a adipiscing ligula, at porta metus. Vivamus varius elit vel quam feugiat, non varius elit pretium. Sed viverra consequat tellus, eget sodales urna hendrerit ut. Curabitur sit amet risus blandit, tempus lectus ut, molestie arcu. Mauris erat felis, aliquam sed augue sed, gravida vestibulum nisi. Maecenas eget tincidunt est, at lacinia nulla.</p>